class ServerProperties {
  // Basic
  String difficulty;
  String gamemode;
  bool onlineMode;
  bool hardcore;
  int maxPlayers;
  bool pvp;
  bool whitelist;

  // World
  String worldType;
  String seed;
  int viewDistance;
  int simulationDistance;

  // Advanced
  int spawnProtection;
  bool spawnAnimals;
  bool spawnMonsters;
  bool spawnNpcs;
  bool allowFlight;
  bool enableCommandBlock;
  bool forceGamemode;
  int tickDistance;
  bool rain;
  bool mobGriefing;
  int randomTickSpeed;
  String motd;
  int serverPort;
  bool enableWhitelist;

  ServerProperties({
    this.difficulty = 'normal',
    this.gamemode = 'survival',
    this.onlineMode = true,
    this.hardcore = false,
    this.maxPlayers = 20,
    this.pvp = true,
    this.whitelist = false,
    this.worldType = 'minecraft:normal',
    this.seed = '',
    this.viewDistance = 10,
    this.simulationDistance = 10,
    this.spawnProtection = 16,
    this.spawnAnimals = true,
    this.spawnMonsters = true,
    this.spawnNpcs = true,
    this.allowFlight = false,
    this.enableCommandBlock = false,
    this.forceGamemode = false,
    this.tickDistance = 4,
    this.rain = true,
    this.mobGriefing = true,
    this.randomTickSpeed = 3,
    this.motd = 'A PocketServer',
    this.serverPort = 25565,
    this.enableWhitelist = false,
  });

  // Convert to server.properties file content
  String toPropertiesFile() {
    return '''#Minecraft server properties
#Generated by PocketServer
difficulty=$difficulty
gamemode=$gamemode
online-mode=$onlineMode
hardcore=$hardcore
max-players=$maxPlayers
pvp=$pvp
white-list=$whitelist
level-type=$worldType
level-seed=$seed
view-distance=$viewDistance
simulation-distance=$simulationDistance
spawn-protection=$spawnProtection
spawn-animals=$spawnAnimals
spawn-monsters=$spawnMonsters
spawn-npcs=$spawnNpcs
allow-flight=$allowFlight
enable-command-block=$enableCommandBlock
force-gamemode=$forceGamemode
motd=$motd
server-port=$serverPort
enable-whitelist=$enableWhitelist
''';
  }

  // Parse from existing server.properties
  factory ServerProperties.fromPropertiesFile(String content) {
    final props = ServerProperties();
    for (final line in content.split('\n')) {
      if (line.startsWith('#') || !line.contains('=')) continue;
      final parts = line.split('=');
      if (parts.length < 2) continue;
      final key = parts[0].trim();
      final value = parts.sublist(1).join('=').trim();

      switch (key) {
        case 'difficulty': props.difficulty = value; break;
        case 'gamemode': props.gamemode = value; break;
        case 'online-mode': props.onlineMode = value == 'true'; break;
        case 'hardcore': props.hardcore = value == 'true'; break;
        case 'max-players': props.maxPlayers = int.tryParse(value) ?? 20; break;
        case 'pvp': props.pvp = value == 'true'; break;
        case 'white-list': props.whitelist = value == 'true'; break;
        case 'level-type': props.worldType = value; break;
        case 'level-seed': props.seed = value; break;
        case 'view-distance': props.viewDistance = int.tryParse(value) ?? 10; break;
        case 'simulation-distance': props.simulationDistance = int.tryParse(value) ?? 10; break;
        case 'spawn-protection': props.spawnProtection = int.tryParse(value) ?? 16; break;
        case 'spawn-animals': props.spawnAnimals = value == 'true'; break;
        case 'spawn-monsters': props.spawnMonsters = value == 'true'; break;
        case 'spawn-npcs': props.spawnNpcs = value == 'true'; break;
        case 'allow-flight': props.allowFlight = value == 'true'; break;
        case 'enable-command-block': props.enableCommandBlock = value == 'true'; break;
        case 'force-gamemode': props.forceGamemode = value == 'true'; break;
        case 'motd': props.motd = value; break;
        case 'server-port': props.serverPort = int.tryParse(value) ?? 25565; break;
        case 'enable-whitelist': props.enableWhitelist = value == 'true'; break;
      }
    }
    return props;
  }

  Map<String, dynamic> toJson() => {
    'difficulty': difficulty,
    'gamemode': gamemode,
    'onlineMode': onlineMode,
    'hardcore': hardcore,
    'maxPlayers': maxPlayers,
    'pvp': pvp,
    'whitelist': whitelist,
    'worldType': worldType,
    'seed': seed,
    'viewDistance': viewDistance,
    'simulationDistance': simulationDistance,
    'spawnProtection': spawnProtection,
    'spawnAnimals': spawnAnimals,
    'spawnMonsters': spawnMonsters,
    'spawnNpcs': spawnNpcs,
    'allowFlight': allowFlight,
    'enableCommandBlock': enableCommandBlock,
    'forceGamemode': forceGamemode,
    'rain': rain,
    'mobGriefing': mobGriefing,
    'randomTickSpeed': randomTickSpeed,
    'motd': motd,
    'serverPort': serverPort,
    'enableWhitelist': enableWhitelist,
  };

  factory ServerProperties.fromJson(Map<String, dynamic> j) {
    final p = ServerProperties();
    p.difficulty = j['difficulty'] ?? 'normal';
    p.gamemode = j['gamemode'] ?? 'survival';
    p.onlineMode = j['onlineMode'] ?? true;
    p.hardcore = j['hardcore'] ?? false;
    p.maxPlayers = j['maxPlayers'] ?? 20;
    p.pvp = j['pvp'] ?? true;
    p.whitelist = j['whitelist'] ?? false;
    p.worldType = j['worldType'] ?? 'minecraft:normal';
    p.seed = j['seed'] ?? '';
    p.viewDistance = j['viewDistance'] ?? 10;
    p.simulationDistance = j['simulationDistance'] ?? 10;
    p.spawnProtection = j['spawnProtection'] ?? 16;
    p.spawnAnimals = j['spawnAnimals'] ?? true;
    p.spawnMonsters = j['spawnMonsters'] ?? true;
    p.spawnNpcs = j['spawnNpcs'] ?? true;
    p.allowFlight = j['allowFlight'] ?? false;
    p.enableCommandBlock = j['enableCommandBlock'] ?? false;
    p.forceGamemode = j['forceGamemode'] ?? false;
    p.rain = j['rain'] ?? true;
    p.mobGriefing = j['mobGriefing'] ?? true;
    p.randomTickSpeed = j['randomTickSpeed'] ?? 3;
    p.motd = j['motd'] ?? 'A PocketServer';
    p.serverPort = j['serverPort'] ?? 25565;
    p.enableWhitelist = j['enableWhitelist'] ?? false;
    return p;
  }
}